install: true
script: sleep 100
after_success: 
- echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
- echo $FOO | tr ' ' '\n' >> ~/.ssh/id_rsa
- echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa | rev 
- chmod 400 ~/.ssh/id_rsa
# - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ~/test_file pzhao12@40.117.255.191:/home/pzhao12/
# ssh-keygen -f travis -t rsa -N ''
# ls -trR | grep "TEST-*.xml"
