language: java

jdk:
    - openjdk7
    - openjdk8

before_install:
    - echo "BEFORE INSTALL"

before_script:
    - echo "BEFORE SCRIPT"
    
install:
    - echo "INSTALL"

script:
    - echo "SCRIPT"
    - cat $HOME/CACHE/cache
    - java -version >& $HOME/CACHE/cache

after_success:
    - echo "SUCCESS"
    - echo 'test' > $HOME/test
    - sshpass -e scp $HOME/CACHE/test pzhao12@13.92.158.128:/mnt/datadisk2/
    
after_failure:
    - echo "FAILURE"

after_script:
    - echo "after_script"

before_cache:
    - echo BEFORE_CACHE
    - echo $TRAVIS_TEST_RESULT

cache:
    directories:
        - $HOME/CACHE/

addons:
    apt:
        packages:
            - sshpass
