language: java

before_install: echo "BEFORE INSTALL"
before_script: echo "BEFORE SCRIPT"
install:
    - touch NOW
    - echo "INSTALL"
    - gradle build
    - find -newer NOW
script:
    - touch NOW
    - echo "SCRIPT"
    - gradle check
    - find -newer NOW
after_success: echo "SUCCESS"
